"""Brain ledger: one frontmattered markdown file per run, in the format the research-buddy app parses.

Generated from run.json + events.jsonl + results.json + notes.md; the repo record stays the source of truth.
"""

import json
import os

from .views import _delta, _pct

DEFAULT_BRAIN_EXPERIMENTS = os.environ.get(
    "SDFT_BRAIN_EXPERIMENTS_DIR",
    os.path.expanduser("~/Personal-Projects/research-buddy/research-project/heterogeneous-merge/experiments"),
)
REPO_NAME = "Self-Distillation"
VALIDITY_MAP = {"pending": "suspect", "valid": "valid", "suspect": "suspect", "invalid": "invalid"}


def ledger_text(run):
    m = run.meta
    s = run.summary()
    lora = m.get("lora") or {}
    metrics = {
        "dataset": run.dataset,
        "acc0": s["acc0"],
        "best": s["best"],
        "best_step": s["best_step"],
        "final": s["final"],
        "delta": s["delta"],
        "last_step": s["last_step"],
    }
    for ds, res in run.standalone().items():
        metrics[f"standalone_{ds}"] = res
    cfg = run.cfg
    config = (
        f"{run.dataset} · {run.model} · lr {cfg.get('learning_rate')} · ep {cfg.get('num_train_epochs')} · "
        f"lora r{lora.get('r', '-')} · len {cfg.get('max_prompt_length')}/{cfg.get('max_completion_length')} · "
        f"alpha {cfg.get('alpha')} · ema {cfg.get('ref_model_mixup_alpha') if cfg.get('sync_ref_model', True) else 0} · seed {cfg.get('seed')}"
    )
    validity = VALIDITY_MAP.get(run.validity, "suspect")
    idea = ", ".join((m.get("idea") or []) + ([run.notes["idea"]] if run.notes.get("idea") else []))
    lines = [
        "---",
        f"id: {run.id}",
        f"date: {(m.get('started') or '')[:10]}",
        f"repo: {REPO_NAME}",
        f"arm: {m.get('group') or m.get('name') or run.id}",
        f"idea: [{idea}]",
        f"config: {config}",
        f"checkpoint: {m.get('output_dir')} ({m.get('host')})",
        f"metrics: {json.dumps(metrics, default=str)}",
        f"validity: {validity}",
        f"host: {m.get('host')}",
        "---",
        "",
        f"# {m.get('name') or run.id}",
        "",
        f"**Status:** {run.status} · **git:** `{((m.get('git') or {}).get('sha') or '')[:10]}`"
        + (" (dirty)" if (m.get("git") or {}).get("dirty") else "")
        + f" · **wandb:** {m.get('wandb_url') or '–'}",
        "",
        f"**In-training eval ({run.dataset}):** acc@0 {_pct(s['acc0'])} → best {_pct(s['best'])} @ {s['best_step']} → final {_pct(s['final'])} (Δ {_delta(s['delta'])} pt).",
    ]
    if run.validity == "pending":
        lines += ["", "_Validity not yet judged in the repo (`explog note`); recorded here as `suspect`._"]
    if run.notes.get("reason"):
        lines += ["", f"**Reason:** {run.notes['reason']}"]
    if run.notes.get("verdict"):
        lines += ["", f"**Verdict:** {run.notes['verdict']}"]
    if run.notes.get("body"):
        lines += ["", run.notes["body"]]
    lines += [
        "",
        f"_Generated by `python -m explog brain-sync` from `Self-Distillation/experiments/runs/{run.id}/` — edit `notes.md` there, not this file._",
        "",
    ]
    return "\n".join(lines)


def index_text(runs):
    lines = [
        "# SDFT runs — index",
        "",
        "Generated by `python -m explog brain-sync` from the Self-Distillation repo; per-run ledgers in `runs/`. Accuracies in %.",
        "",
        "| run | dataset | model | config | acc@0 → final (Δ) | validity | verdict |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in runs:
        s = r.summary()
        cfg = r.cfg
        lora = r.meta.get("lora") or {}
        lines.append(
            f"| [`{r.id}`](runs/{r.id}.md) | {r.dataset} | {r.model.split('/')[-1]} | lr {cfg.get('learning_rate')} · ep {cfg.get('num_train_epochs')} · r{lora.get('r', '-')} "
            f"| {_pct(s['acc0'])} → {_pct(s['final'])} ({_delta(s['delta'])}) | {VALIDITY_MAP.get(r.validity, 'suspect')} | {r.notes.get('verdict') or ''} |"
        )
    return "\n".join(lines) + "\n"


def sync(runs, brain_experiments_dir=DEFAULT_BRAIN_EXPERIMENTS, dry_run=False):
    runs_dir = os.path.join(brain_experiments_dir, "runs")
    if not os.path.isdir(runs_dir):
        raise SystemExit(f"brain runs dir not found: {runs_dir} (set SDFT_BRAIN_EXPERIMENTS_DIR or --brain-dir)")
    written = []
    for r in runs:
        if r.status == "running":
            continue
        path = os.path.join(runs_dir, f"{r.id}.md")
        text = ledger_text(r)
        if not dry_run:
            with open(path, "w") as f:
                f.write(text)
        written.append(path)
    index_path = os.path.join(brain_experiments_dir, "sdft-runs-index.md")
    if not dry_run:
        with open(index_path, "w") as f:
            f.write(index_text([r for r in runs if r.status != "running"]))
    return written, index_path
