"""Generated views: the INDEX table, `show`, `compare`, `check`."""

import os
from collections import defaultdict
from datetime import datetime

from .records import REPO_ROOT, load_runs

INDEX_PATH = os.path.join(REPO_ROOT, "experiments", "INDEX.md")
STATUS_GLYPH = {"finished": "✓", "running": "⏳", "failed": "✗", "killed": "☠"}


def _f(x, nd=4):
    """General number format: 5e-05, 1, 0.0323, 0.43 — never 0.000 for a small learning rate."""
    if x is None:
        return "–"
    if isinstance(x, float):
        return f"{x:.{nd}g}"
    return str(x)


def _pct(x):
    return "–" if x is None else f"{100 * x:.1f}"


def _delta(x):
    return "–" if x is None else f"{100 * x:+.1f}"


def _short_model(name):
    return name.split("/")[-1] if name else "?"


def _len(run):
    return f"{run.cfg.get('max_prompt_length', '?')}/{run.cfg.get('max_completion_length', '?')}"


def _lr(run):
    lr = run.cfg.get("learning_rate")
    return f"{lr:.0e}".replace("e-0", "e-") if isinstance(lr, (int, float)) else "–"


def _run_cell(run):
    cell = f"`{run.id}`"
    if run.validity == "invalid":
        cell = f"~~{cell}~~"
    url = run.meta.get("wandb_url")
    return f"{cell} [w]({url})" if url else cell


def _teacher(run):
    if not run.cfg.get("sync_ref_model", True) or run.cfg.get("ref_model_mixup_alpha") in (0, 0.0):
        return "frozen"
    return f"ema {run.cfg.get('ref_model_mixup_alpha')}"


def _divergence(run):
    a = run.cfg.get("alpha")
    return {0: "fKL", 0.0: "fKL", 1: "rKL", 1.0: "rKL"}.get(a, f"jsd{a}")


def _group_rows(runs):
    """Markdown table for one dataset's runs."""
    header = (
        "| run | date | st | model | teacher · div | lr | ep | r | len | steps | acc@0 | best (step) | final | Δ | validity | verdict |\n"
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n"
    )
    rows = []
    for r in runs:
        s = r.summary()
        lora = r.meta.get("lora") or {}
        date = (r.meta.get("started") or "")[:10]
        best = "–" if s["best"] is None else f"{_pct(s['best'])} ({s['best_step']})"
        verdict = (r.notes.get("verdict") or "").replace("|", "/")
        if r.validity == "invalid" and r.notes.get("reason"):
            verdict = f"INVALID: {r.notes['reason']} — {verdict}".rstrip(" —")
        rows.append(
            f"| {_run_cell(r)} | {date} | {STATUS_GLYPH.get(r.status, '?')} | {_short_model(r.model)} | {_teacher(r)} · {_divergence(r)} "
            f"| {_lr(r)} | {_f(r.cfg.get('num_train_epochs'), 1)} | {lora.get('r', 'full')} | {_len(r)} | {_f(s['last_step'])} "
            f"| {_pct(s['acc0'])} | {best} | {_pct(s['final'])} | {_delta(s['delta'])} | {r.validity} | {verdict} |"
        )
    return header + "\n".join(rows) + "\n"


def render_index(runs):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    out = [
        "# Experiment index",
        "",
        f"Generated by `python -m explog table` on {now} from `experiments/runs/` — do not edit; edit a run's `notes.md` and regenerate.",
        f"{len(runs)} runs. Accuracies in %, from the in-training eval on the run's own dataset (`acc@0` = step-0 baseline). "
        "`st`: ✓ finished · ⏳ running · ✗ failed · ☠ killed. `[w]` = wandb. Struck-through = `validity: invalid`.",
        "",
    ]
    if not runs:
        out.append("_No runs recorded yet._")
        return "\n".join(out) + "\n"

    latest = runs[:5]
    out += ["## Latest", ""]
    for r in latest:
        s = r.summary()
        out.append(
            f"- {_run_cell(r)} — {r.dataset}, {STATUS_GLYPH.get(r.status, '?')} {r.status}, "
            f"final {_pct(s['final'])} (Δ {_delta(s['delta'])}), {r.validity}"
            + (f" — {r.notes['verdict']}" if r.notes.get("verdict") else "")
        )
    out.append("")

    by_ds = defaultdict(list)
    for r in runs:
        by_ds[r.dataset].append(r)
    for ds in sorted(by_ds):
        out += [f"## {ds}", "", _group_rows(by_ds[ds])]
        groups = defaultdict(list)
        for r in by_ds[ds]:
            if r.meta.get("group"):
                groups[r.meta["group"]].append(r)
        for g in sorted(groups):
            if len(groups[g]) > 1:
                out += [f"### sweep `{g}`", "", _group_rows(sorted(groups[g], key=lambda r: r.cfg.get("learning_rate") or 0))]

    # standalone evaluations (forgetting / cross-dataset), if any run has them
    with_results = [r for r in runs if r.results]
    if with_results:
        datasets = sorted({res["dataset"] for r in with_results for res in r.results})
        out += ["## Standalone evaluations (results.json)", "", "| run | " + " | ".join(datasets) + " |", "|---|" + "---|" * len(datasets)]
        for r in with_results:
            st = r.standalone()
            out.append("| " + _run_cell(r) + " | " + " | ".join(_pct(st.get(d, {}).get("accuracy")) for d in datasets) + " |")
        out.append("")
    return "\n".join(out) + "\n"


def write_index(path=INDEX_PATH, runs=None):
    runs = load_runs() if runs is None else runs
    os.makedirs(os.path.dirname(path), exist_ok=True)
    text = render_index(runs)
    with open(path, "w") as f:
        f.write(text)
    return path, len(runs)


def show(run):
    r_s = run.summary()
    m = run.meta
    lines = [
        f"# {run.id}",
        f"name: {m.get('name')}   group: {m.get('group')}   tags: {m.get('tags')}   idea: {m.get('idea')}",
        f"status: {run.status}   started: {m.get('started')}   ended: {m.get('ended')}   host: {m.get('host')}   gpu: {m.get('gpu')}",
        f"model: {run.model} @ {(m.get('model') or {}).get('revision')}",
        f"data: {run.dataset} rows={(m.get('data') or {}).get('rows')} fp={(m.get('data') or {}).get('fingerprint')}",
        f"git: {(m.get('git') or {}).get('sha')} ({(m.get('git') or {}).get('branch')}) dirty={(m.get('git') or {}).get('dirty')} untracked={len((m.get('git') or {}).get('untracked') or [])}",
        f"lora: {m.get('lora')}   parent: {m.get('parent_run')}",
        f"env: {m.get('env')}",
        f"wandb: {m.get('wandb_url')}",
        f"output_dir: {m.get('output_dir')}",
        f"cmd: {m.get('cmd')}",
        "",
        "## config",
    ]
    lines += [f"  {k}: {v}" for k, v in run.cfg.items()]
    lines += ["", "## in-training eval"]
    for ds in run.eval_datasets():
        curve = run.eval_curve(ds)
        lines.append(f"  {ds}: " + "  ".join(f"{step}:{_pct(acc)}" for step, acc in curve))
    lines.append(
        f"  summary ({run.dataset}): acc@0 {_pct(r_s['acc0'])}  best {_pct(r_s['best'])}@{r_s['best_step']}  final {_pct(r_s['final'])}@{r_s['final_step']}  Δ {_delta(r_s['delta'])}  last_step {r_s['last_step']}  final_loss {_f(r_s['final_loss'], 4)}"
    )
    if run.results:
        lines += ["", "## standalone evaluations"]
        for res in run.results:
            lines.append(f"  {res['dataset']}: {res.get('metrics')}  ckpt={res.get('checkpoint')}  {res.get('time')}")
    lines += ["", "## notes"]
    for k in ("validity", "reason", "verdict", "idea"):
        lines.append(f"  {k}: {run.notes.get(k, '')}")
    if run.notes.get("body"):
        lines += ["", run.notes["body"]]
    if m.get("error"):
        lines += ["", f"## error", m["error"]]
    return "\n".join(lines) + "\n"


def compare(runs):
    keys = sorted({k for r in runs for k in r.cfg} | {"model", "dataset", "lora_r"})
    lines = ["| field | " + " | ".join(f"`{r.id}`" for r in runs) + " |", "|---|" + "---|" * len(runs)]

    def val(r, k):
        if k == "model":
            return _short_model(r.model)
        if k == "dataset":
            return r.dataset
        if k == "lora_r":
            return (r.meta.get("lora") or {}).get("r", "full")
        return r.cfg.get(k)

    for k in keys:
        vals = [val(r, k) for r in runs]
        mark = "**" if len({str(v) for v in vals}) > 1 else ""
        lines.append(f"| {mark}{k}{mark} | " + " | ".join(_f(v) for v in vals) + " |")
    lines += ["", "| metric | " + " | ".join(f"`{r.id}`" for r in runs) + " |", "|---|" + "---|" * len(runs)]
    summaries = [r.summary() for r in runs]
    for k, fmt in (("acc0", _pct), ("best", _pct), ("best_step", _f), ("final", _pct), ("delta", _delta), ("last_step", _f), ("final_loss", lambda x: _f(x, 4))):
        lines.append(f"| {k} | " + " | ".join(fmt(s[k]) for s in summaries) + " |")
    lines.append("| validity | " + " | ".join(r.validity for r in runs) + " |")
    lines.append("| git | " + " | ".join(((r.meta.get('git') or {}).get('sha') or '')[:8] + ("*" if (r.meta.get('git') or {}).get('dirty') else "") for r in runs) + " |")
    return "\n".join(lines) + "\n"


def check(runs, running_hours=24):
    problems = []
    now = datetime.now().astimezone()
    for r in runs:
        m = r.meta
        if r.status == "running" and m.get("started"):
            try:
                started = datetime.fromisoformat(m["started"])
                if (now - started).total_seconds() > running_hours * 3600:
                    problems.append((r.id, f"still 'running' after {running_hours} h — killed without finalize?"))
            except ValueError:
                pass
        if r.status == "finished":
            if not r.eval_curve() and not r.results:
                problems.append((r.id, "finished with no eval curve and no results.json"))
            if r.validity == "pending":
                problems.append((r.id, "finished but validity still pending — judge it (explog note)"))
        if r.validity == "invalid" and not r.notes.get("reason"):
            problems.append((r.id, "invalid without a reason"))
        if (m.get("git") or {}).get("dirty") and not os.path.exists(os.path.join(r.dir, "code.patch")):
            problems.append((r.id, "dirty tree but no code.patch"))
    return problems
